export const Icons = {
  Vault: require('./vault.png'),
  Security: require('./security.png'),
  Diamond: require('./diamond.png'),
  Setting: require('./setting.png'),
  ActiveVault: require('./active-vault.png'),
  ActiveSecurity: require('./active-security.png'),
  ActiveDiamond: require('./active-diamond.png'),
  ActiveSetting: require('./active-setting.png'),
  Hide: require('./hidden.png'),
  UnHide: require('./unhidden.png'),
  Logo: require('./logo.png'),
  Mail: require('./mail.png'),
  Lock: require('./lock.png'),
};
