export const Icons = {
  Vault: require('./vault.png'),
  Security: require('./security.png'),
  Diamond: require('./diamond.png'),
  Setting: require('./setting.png'),
  ActiveVault: require('./active-vault.png'),
  ActiveSecurity: require('./active-security.png'),
  ActiveDiamond: require('./active-diamond.png'),
  ActiveSetting: require('./active-setting.png'),
  Hide: require('./hidden.png'),
  UnHide: require('./unhidden.png'),
  Logo: require('./logo.png'),
  Mail: require('./mail.png'),
  Lock: require('./lock.png'),
  EmptyAll: require('./empty-all.png'),
  EmptyContacts: require('./empty-contacts.png'),
  EmptyCreditCard: require('./empty-credit-card.png'),
  EmptyNote: require('./empty-note.png'),
  EmptyPassword: require('./empty-password.png'),
  Generate: require('./generate.png'),
  Plane: require('./plane.png'),
  Access: require('./access.png'),
  Share: require('./share.png'),
  Computer: require('./computer.png'),
  Technical: require('./technical.png'),
};
