export enum Screens {
  BottomTab = 'BottomTab',
  Settings = 'Settings',
  Vault = 'Vault',
  Security = 'Security',
  Update = 'Update',
  Authentication = 'Authentication',
  Authenticated = 'Authenticated',
  Walkthrough = 'Walkthrough',
  Login = 'Login',
  Register = 'Register',
  VaultStackNavigator = 'VaultStackNavigator',
  AddNewItem = 'AddNewItem',
  Add = 'Add',
  SecurityStackNavigator = 'SecurityStackNavigator',
  GeneratePassword = 'GeneratePassword',
  PasswordHistory = 'PasswordHistory',
  SettingsStackNavigator = 'SettingsStackNavigator',
  Account = 'Account',
  ChangePassword = 'ChangePassword',
  SecuritySettings = 'SecuritySettings',
  Options = 'Options',
  RegisterSuccess = 'RegisterSuccess',
}
