export enum Screens {
  BottomTab = 'BottomTab',
  Settings = 'Settings',
  Vault = 'Vault',
  Security = 'Security',
  Update = 'Update',
  Authentication = 'Authentication',
  Authenticated = 'Authenticated',
  Walkthrough = 'Walkthrough',
  Login = 'Login',
  Register = 'Register',
  VaultStackNavigator = 'VaultStackNavigator',
  AddNewItem = 'AddNewItem',
  Add = 'Add',
}
